# Generated by Django 4.0.3 on 2022-05-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(default=1, max_length=256, verbose_name='文章摘要'),
            preserve_default=False,
        ),
    ]
