# Generated by Django 4.0.3 on 2022-05-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_article_abstract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='delete_status',
        ),
        migrations.AddField(
            model_name='article',
            name='publish_status',
            field=models.BooleanField(choices=[(False, '未发布'), (True, '发布')], default=False, verbose_name='发布状态'),
        ),
    ]
