# Generated by Django 4.0.3 on 2022-05-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_remove_article_delete_status_article_publish_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='delete_status',
            field=models.BooleanField(choices=[(False, '未删除'), (True, '删除')], default=False, verbose_name='文章状态'),
        ),
    ]
