# Generated by Django 4.0.3 on 2022-05-22 12:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='文章内容'),
        ),
    ]
