# Generated by Django 4.0.3 on 2022-06-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_articledetail_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='资源名称')),
                ('count', models.IntegerField(verbose_name='资源简介')),
                ('resource', models.FileField(max_length=1024, upload_to='resource', verbose_name='资源文件')),
            ],
        ),
    ]
