# Generated by Django 4.0.3 on 2022-06-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='count',
        ),
        migrations.AddField(
            model_name='resource',
            name='introduction',
            field=models.CharField(default=222, max_length=128, verbose_name='资源简介'),
            preserve_default=False,
        ),
    ]
