# Generated by Django 4.0.3 on 2022-06-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_remove_resource_count_resource_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '文献资料'), (1, '代码资料'), (2, '数据集')], default=1, verbose_name='文献类别'),
            preserve_default=False,
        ),
    ]
