# Generated by Django 4.0.3 on 2022-06-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_resource_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Article',
            new_name='article',
        ),
    ]
