# Generated by Django 4.0.3 on 2022-06-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_rename_article_comment_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_time',
            new_name='time',
        ),
    ]
